dist: trusty
language: python
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    # This is temporarily disabled due to lack of travis support
    #- TOXENV=pypy
    - TOXENV=docs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
  - python --version
  - python3 --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
webhooks:
  urls:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
